FROM grafana/grafana:latest

COPY ./dashboards /var/lib/grafana/dashboards
COPY ./provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY ./provisioning/datasources /etc/grafana/provisioning/datasources
